--- 

- name: multi node k3s lead node playbook
  hosts: localhost
  become: true
  become_user: root
  vars_files:
    - /etc/ansible/vars/static/vars-static-lead.yml
    - /etc/ansible/vars/dynamic/vars-dynamic-control.yml
    - /etc/ansible/vars/user/ansible-vars.yml

  roles:
    - k3s
