---

- name: multi node k3s worker node playbook
  hosts: workers
  become: true
  become_user: root
  vars_files:
    - /etc/ansible/vars/static/vars-static-worker.yml
    - /etc/ansible/vars/dynamic/vars-dynamic-worker.yml
    - /etc/ansible/vars/user/ansible-vars.yml

  roles:
    - k3s
