---

- name: single node k3s cluster playbook
  hosts: localhost
  become: true
  become_user: root
  vars_files: 
    - /etc/ansible/vars/static/vars-static.yml
    - /etc/ansible/vars/dynamic/vars-dynamic.yml
    - /etc/ansible/vars/user/ansible-vars.yml

  roles:
    - kube
